spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/purchase_tracker
spring.datasource.username=purchase_tracker_dev
spring.datasource.password=purchase_tracker_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
 
jwt.secret=${JWT_SECRET}
# 1 hour expiry
jwt.expiration-ms=3600000

