spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/purchase_tracker
spring.datasource.username=purchase_tracker_dev
spring.datasource.password=purchase_tracker_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver